import { useEffect, useState } from 'react';
import { LiveMap } from '../../components/LiveMap';
import { getRouteByWariId, saveRoute, type WariRouteRecord } from '../../services/routes';
import { fetchRoadRoute, geocodePlace, type RoutePoint } from '../../services/routing';

type RouteSetupPageProps = { wariId?: string; wariCode?: string; wariName?: string; source?: string; destination?: string; onComplete?: () => void };
const geometryToPoints = (geometry: unknown): RoutePoint[] => { const coordinates = Array.isArray(geometry) ? geometry : (geometry as { coordinates?: unknown[] } | null)?.coordinates; if (!Array.isArray(coordinates)) return []; return coordinates.map((item) => { if (!Array.isArray(item)) return null; const first = Number(item[0]); const second = Number(item[1]); return Math.abs(first) <= 90 ? { lat: first, lng: second } : { lat: second, lng: first }; }).filter((point): point is RoutePoint => Boolean(point)); };

export function RouteSetupPage({ wariId = '', wariCode = '', wariName = '', source = '', destination = '', onComplete }: RouteSetupPageProps) {
  const [route, setRoute] = useState<WariRouteRecord | null>(null); const [points, setPoints] = useState<RoutePoint[]>([]); const [sourcePoint, setSourcePoint] = useState<RoutePoint | null>(null); const [destinationPoint, setDestinationPoint] = useState<RoutePoint | null>(null); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  useEffect(() => { if (!wariId) return; getRouteByWariId(wariId).then((saved) => { setRoute(saved); if (saved?.source_lat != null && saved.source_lng != null) setSourcePoint({ lat: saved.source_lat, lng: saved.source_lng }); if (saved?.destination_lat != null && saved.destination_lng != null) setDestinationPoint({ lat: saved.destination_lat, lng: saved.destination_lng }); const savedPoints = geometryToPoints(saved?.road_geometry); if (savedPoints.length > 1) setPoints(savedPoints); }).catch((loadError) => console.error('Unable to load saved route', loadError)); }, [wariId]);
  const calculateRoute = async () => { setLoading(true); setError(''); setMessage(''); try { const start = sourcePoint ?? await geocodePlace(source); const end = destinationPoint ?? await geocodePlace(destination); const road = await fetchRoadRoute([start, end]); setSourcePoint(start); setDestinationPoint(end); setPoints(road.geometry.map(([lat, lng]) => ({ lat, lng }))); setRoute({ id: '', wari_id: wariId, source_lat: start.lat, source_lng: start.lng, destination_lat: end.lat, destination_lng: end.lng, route_points: [start, end], checkpoints: [{ name: source, ...start }, { name: destination, ...end }], road_geometry: road.geometry, total_distance_km: road.distance / 1000, estimated_duration_min: road.duration / 60 }); } catch (routeError) { console.error('Unable to calculate route', routeError); setError('Unable to calculate route.'); } finally { setLoading(false); } };
  const handleSave = async () => { if (!route || !sourcePoint || !destinationPoint) return; setSaving(true); setError(''); try { const saved = await saveRoute({ wari_id: wariId, route_points: [sourcePoint, destinationPoint], checkpoints: [{ name: source, ...sourcePoint }, { name: destination, ...destinationPoint }], source_lat: sourcePoint.lat, source_lng: sourcePoint.lng, destination_lat: destinationPoint.lat, destination_lng: destinationPoint.lng, road_geometry: route.road_geometry, total_distance_km: route.total_distance_km, estimated_duration_min: route.estimated_duration_min }); setRoute(saved); setMessage('Route saved successfully'); } catch (saveError) { console.error('Unable to save route', saveError); setError('Unable to save route.'); } finally { setSaving(false); } };
  return <main className="min-h-screen bg-slate-50 px-4 py-8 text-slate-900 sm:px-6 lg:px-8"><div className="mx-auto max-w-6xl"><section className="rounded-[28px] border border-slate-200 bg-white p-5 shadow-sm sm:p-8"><p className="text-xs font-semibold uppercase tracking-[0.25em] text-sky-600">Configure Route · {wariCode || wariId}</p><h1 className="mt-2 text-3xl font-bold">{wariName || 'Wari route'}</h1><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold text-slate-700">Source<input className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2" value={source} readOnly /></label><label className="text-sm font-semibold text-slate-700">Destination<input className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2" value={destination} readOnly /></label></div><div className="mt-5 flex flex-wrap gap-3"><button type="button" onClick={calculateRoute} disabled={loading} className="rounded-xl bg-sky-600 px-4 py-2.5 text-sm font-semibold text-white">{loading ? 'Calculating route…' : 'Calculate Route'}</button><button type="button" onClick={handleSave} disabled={saving || !route} className="rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white">{saving ? 'Saving…' : 'Save Route'}</button>{message ? <span className="self-center text-sm font-semibold text-emerald-700">{message}</span> : null}{error ? <span className="self-center text-sm font-semibold text-rose-600">{error}</span> : null}</div>{route ? <p className="mt-4 text-sm text-slate-600">{Number(route.total_distance_km ?? 0).toFixed(1)} km · ~{Math.round(Number(route.estimated_duration_min ?? 0) / 60)} hr</p> : null}<div className="mt-6"><LiveMap sourcePosition={sourcePoint} destinationPosition={destinationPoint} routePoints={points} /></div>{message ? <button type="button" onClick={onComplete} className="mt-5 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700">Open Dindi Dashboard</button> : null}</section></div></main>;
}
export default RouteSetupPage;
